accelerate launch train_dreambooth_inpaint.py \
  --pretrained_model_name_or_path="hf-internal-testing/tiny-sdxl-pipe"  \
  --dataset_path="AlekseyKorshuk/product-photography-tiny" \
  --output_dir="./results" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400